# Generated by Django 3.2.25 on 2026-03-30 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0213_auto_20250409_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPublicationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=False, verbose_name='is allowed')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('testcase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_rule', to='judge.problemtestcase', verbose_name='test case')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_test_publication_rules', to='judge.profile', verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'test publication rule',
                'verbose_name_plural': 'test publication rules',
                'db_table': 'test_publication_rule',
            },
        ),
    ]
